name: vault
description: WebDAV / OpenList 私密相册客户端，缓存仅存 App 沙盒。
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.6.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10
  go_router: ^14.6.2
  path_provider: ^2.1.4
  photo_manager: ^3.6.3
  shared_preferences: ^2.3.3
  video_player: ^2.9.2
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
